## Arewa Data Science Academy
### Deep Learning Cohort1.0

#### Name: Sani Aji
#### Email: saniajy@gmail.com
#### Title: Week 1 Solution

### Exercises Solution

###  1. Documentation reading on torch.Tensor and torch.cuda

### 2. Create a random tensor with shape (7, 7)

In [1]:
import torch
random_tensor = torch.rand(size=(7, 7))
random_tensor

tensor([[0.5627, 0.9653, 0.7830, 0.9883, 0.9157, 0.7452, 0.4821],
        [0.6509, 0.0548, 0.6631, 0.6508, 0.9680, 0.7100, 0.4055],
        [0.3630, 0.3003, 0.0906, 0.5850, 0.1413, 0.9465, 0.3483],
        [0.9439, 0.2454, 0.2280, 0.6274, 0.2572, 0.2079, 0.4138],
        [0.2969, 0.7908, 0.2039, 0.8401, 0.4753, 0.0155, 0.1818],
        [0.4098, 0.2100, 0.8066, 0.3678, 0.6347, 0.7687, 0.6345],
        [0.9350, 0.0800, 0.7789, 0.6632, 0.2018, 0.2836, 0.7619]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [2]:
random_tensor_2 =  torch.rand(size=(1, 7))
# Matrix multiplication
torch.matmul(random_tensor, random_tensor_2.T)

tensor([[2.6182],
        [1.8567],
        [1.1997],
        [1.3302],
        [1.4323],
        [1.8134],
        [1.9914]])

### 4. Set the random seed to 0 and do exercises 2 & 3 over again.

In [4]:
RANDOM_SEED=0
torch.manual_seed(seed=RANDOM_SEED)
random_tensor = torch.rand(size=(7, 7))
print(f"Random Tensor:\n{random_tensor}\n")

torch.manual_seed(seed=RANDOM_SEED)
random_tensor_2 =  torch.rand(size=(1, 7))
print(f"Random Tensor2:\n{random_tensor_2}\n")

# Matrix multiplication
torch.matmul(random_tensor, random_tensor_2.T)


Random Tensor:
tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

Random Tensor2:
tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])



tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

### 5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.

In [11]:
#GPU Equivalent for setting Random Seed is torch.cuda.manual_seed()
#to check if we have GPU
torch.cuda.is_available()
#to set the GPU random seed:

RANDOM_SEED=1234
torch.cuda.manual_seed(seed=RANDOM_SEED)




### 6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

In [32]:

torch.manual_seed(1234)
random_tensor1 = torch.rand(size=(2, 3))
random_tensor2 = torch.rand(size=(2, 3))
# Tensor not on GPU
print(random_tensor1, random_tensor1.device)
print(random_tensor2, random_tensor2.device)


tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]]) cpu
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]]) cpu


In [33]:

# Moving them to GPU
device = 'cuda'
random_tensor1_on_GPU= random_tensor1.to(device)
random_tensor2_on_GPU= random_tensor2.to(device)
print(random_tensor1_on_GPU, random_tensor1_on_GPU.device)
print(random_tensor2_on_GPU, random_tensor2_on_GPU.device)

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0') cuda:0
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0') cuda:0


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [46]:
# Matrix multiplication
Matrix_Multiply = torch.matmul(random_tensor1_on_GPU, random_tensor2_on_GPU.T)
Matrix_Multiply


tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [41]:
#Min
print(torch.min(Matrix_Multiply))
#max
print(torch.max(Matrix_Multiply))

tensor(0.3647, device='cuda:0')
tensor(0.5617, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7

In [42]:
#index of min
print(torch.argmin(Matrix_Multiply))

#index of max

print(torch.argmax(Matrix_Multiply))


tensor(0, device='cuda:0')
tensor(3, device='cuda:0')


### 10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [45]:
torch.manual_seed(7)
random_tensor_new = torch.rand((1,1,1,10))
print(random_tensor_new, random_tensor_new.shape)

#to remove the 1 dims, we use squeeze()
random_tensor_new_wo_dims= random_tensor_new.squeeze()
print(random_tensor_new_wo_dims, random_tensor_new_wo_dims.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
